# Generated by Django 3.2.2 on 2022-10-08 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListPryModelo',
            fields=[
                ('ID', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PROYECTO_SAP', models.CharField(db_column='PROYECTO_SAP', max_length=75, verbose_name='Proyecto SAP')),
                ('CEGE_UNIVERSAL', models.CharField(blank=True, db_column='CEGE_UNIVERSAL', max_length=8, null=True, verbose_name='CeGe Universal')),
                ('PROYECTO_GCIA', models.CharField(db_column='PROYECTO_GCIA', max_length=75, unique=True, verbose_name='Proyecto Gcia')),
                ('ESTADO', models.CharField(db_column='ESTADO', max_length=11, verbose_name='Estado')),
                ('ALCANCE', models.TextField(db_column='ALCANCE', max_length=4000, verbose_name='Alcance')),
                ('ANIO_SAP', models.PositiveIntegerField(db_column='ANIO_SAP', verbose_name='Anio SAP')),
                ('PAIS', models.CharField(db_column='PAIS', max_length=2, verbose_name='Pais')),
                ('RED', models.CharField(db_column='RED', max_length=5, verbose_name='Red')),
                ('VALORACION', models.CharField(db_column='VALORACION', max_length=9, verbose_name='Valoracion')),
                ('RESPONSABLE', models.CharField(db_column='RESPONSABLE', max_length=400, verbose_name='Responsable')),
                ('GERENCIA', models.CharField(db_column='GERENCIA', max_length=8, verbose_name='Gerencia')),
                ('FECHA_INICIO_ESTIMADA', models.DateField(db_column='FECHA_INICIO_ESTIMADA', default='9999-12-31', verbose_name='Fecha Inicio Estimada')),
                ('FECHA_FIN_ESTIMADA', models.DateField(db_column='FECHA_FIN_ESTIMADA', default='9999-12-31', verbose_name='Fecha Fin Estimada')),
                ('FECHA_INICIO_REAL', models.DateField(blank=True, db_column='FECHA_INICIO_REAL', default='9999-12-31', verbose_name='Fecha Inicio Real')),
                ('FECHA_FIN_REAL', models.DateField(blank=True, db_column='FECHA_FIN_REAL', default='9999-12-31', verbose_name='Fecha Fin Real')),
                ('FECHA_CANCELACION', models.DateField(blank=True, db_column='FECHA_CANCELACION', default='9999-12-31', verbose_name='Fecha Cancelacion')),
                ('MOTIVO_CANCELACION', models.TextField(blank=True, db_column='MOTIVO_CANCELACION', max_length=4000, null=True, verbose_name='Motivo Cancelacion')),
                ('USUARIO_REPORTE', models.CharField(db_column='USUARIO_REPORTE', default='system', max_length=10, verbose_name='Usuario reporte')),
                ('FECHA_CREACION', models.DateField(db_column='FECHA_CREACION', default='9999-12-31', verbose_name='Fecha Creacion')),
            ],
            options={
                'db_table': 'WEB_DAILYPRYCORE_LISTADO',
            },
        ),
        migrations.CreateModel(
            name='SeguiPryModelo',
            fields=[
                ('ID', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('USUARIO_REPORTE', models.CharField(db_column='USUARIO_REPORTE', default='system', max_length=10, verbose_name='Usuario reporte')),
                ('FECHA_REPORTE', models.DateField(db_column='FECHA_REPORTE', default='9999-12-31', verbose_name='Fecha Reporte')),
                ('FASE_COMPRAS', models.CharField(db_column='FASE_COMPRAS', max_length=10, verbose_name='Fase Compras')),
                ('FASE_PREPARACION', models.CharField(db_column='FASE_PREPARACION', max_length=10, verbose_name='Fase Preparacion')),
                ('FASE_IMPLEMENTACION', models.CharField(db_column='FASE_IMPLEMENTACION', max_length=10, verbose_name='Fase Implementacion')),
                ('FASE_PRUEBAS', models.CharField(db_column='FASE_PRUEBAS', max_length=10, verbose_name='Fase Pruebas')),
                ('FASE_PRODUCCION', models.CharField(db_column='FASE_PRODUCCION', max_length=10, verbose_name='Fase Produccion')),
                ('SITUACION', models.TextField(db_column='SITUACION', max_length=4000, verbose_name='Situacion')),
                ('FECHA_REPLAN', models.DateField(blank=True, db_column='FECHA_REPLAN', default='9999-12-31', verbose_name='Fecha RePlan')),
                ('MOTIVO_REPLAN', models.TextField(blank=True, db_column='MOTIVO_REPLAN', max_length=4000, null=True, verbose_name='Motivo RePlan')),
                ('FECHA_STANDBY', models.DateField(blank=True, db_column='FECHA_STANDBY', default='9999-12-31', verbose_name='Fecha Stand By')),
                ('MOTIVO_STANDBY', models.TextField(blank=True, db_column='MOTIVO_STANDBY', max_length=4000, null=True, verbose_name='Motivo Stand By')),
                ('PROYECTO_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serviciosRed.listprymodelo', verbose_name='ID Proyecto')),
            ],
            options={
                'db_table': 'WEB_DAILYPRYCORE_SEGUIMIENTO',
            },
        ),
    ]
