# Generated by Django 3.2.2 on 2022-10-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pospreFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOC_POSPRE', models.FileField(upload_to='gcia_plan/capex/files')),
            ],
            options={
                'db_table': 'WEB_FILEPOSPRE',
            },
        ),
        migrations.CreateModel(
            name='pospreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POSPRE', models.CharField(max_length=12, verbose_name='POSPRE')),
                ('DESCRIPCION_POSPRE', models.CharField(max_length=75, verbose_name='DESCRIPCION_POSPRE')),
                ('RUBRO', models.CharField(max_length=100, verbose_name='RUBRO')),
                ('RUBRO_1', models.CharField(max_length=100, verbose_name='RUBRO_1')),
                ('RED', models.CharField(max_length=2, verbose_name='RED')),
            ],
            options={
                'db_table': 'WEB_DAILYPOSPRE',
            },
        ),
        migrations.CreateModel(
            name='proveedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NROPROVEEDOR', models.IntegerField(verbose_name='NROPROVEEDOR')),
                ('PROVEEDOR', models.CharField(max_length=50, verbose_name='PROVEEDOR')),
                ('COMEX', models.IntegerField(verbose_name='COMEX')),
            ],
            options={
                'db_table': 'WEB_DAILYPROVEEDORES',
            },
        ),
        migrations.CreateModel(
            name='pryCarryOverFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOC_PRY_CO', models.FileField(upload_to='gcia_plan/capex/files')),
            ],
            options={
                'db_table': 'WEB_FILECARRYOVER',
            },
        ),
        migrations.CreateModel(
            name='pryCarryOverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POSPRE', models.CharField(max_length=12, verbose_name='POSPRE')),
                ('CEGE', models.CharField(max_length=10, verbose_name='CEGE')),
                ('DENOM_CEGE', models.CharField(max_length=100, verbose_name='DENOM_CEGE')),
                ('PRESUPUESTO_ANIO', models.IntegerField()),
                ('FONDO', models.CharField(max_length=10, verbose_name='FONDO')),
                ('CAPEX_FINAL', models.FloatField()),
            ],
            options={
                'db_table': 'WEB_DAILYCARRYOVER',
            },
        ),
        migrations.CreateModel(
            name='tasasCambioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pais', models.CharField(max_length=10)),
                ('tc_plan', models.FloatField(blank=True, null=True)),
                ('tc_revision', models.FloatField(blank=True, null=True)),
                ('tc_proyectada', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WEB_DAILYTASASCAMBIO',
                'ordering': ['fecha', 'pais'],
            },
        ),
    ]
