# Generated by Django 3.2.2 on 2022-10-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListApiModelo',
            fields=[
                ('ID', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(db_column='NOMBRE', max_length=100, verbose_name='Nombre')),
                ('DESCRIPCION', models.TextField(db_column='DESCRIPCION', max_length=4000, verbose_name='Descripcion')),
                ('EJEMPLO_JSON', models.TextField(db_column='EJEMPLO_JSON', max_length=5000, verbose_name='Ejemplo_JSON')),
                ('LINK', models.CharField(db_column='LINK', max_length=100, verbose_name='Link')),
                ('PUBLICACION', models.BooleanField()),
            ],
            options={
                'db_table': 'WEB_APIS',
            },
        ),
    ]
